server:
  port: 8081


#  ai 配置
spring:
  datasource:
    url: jdbc:sqlite:\\OmniAI\\db\\omni_ai.db # 改为数据库路径
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
      hibernate:
        use-schema-for-sequence: false
        use-new-id-generator-mappings: false
    show-sql: true
